version: "3"
services:
  db:
    image: mysql:5.7
    #container_name: "nannal_mysql57"
    volumes:
      - ./db/mysql:/var/lib/mysql2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nannal
      MYSQL_DATABASE: nannal_wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: nannal

  wordpress:
    image: wordpress:latest
    #container_name: "nanal_wordpress"
    volumes:
      - ./wordpress/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: nannal_wordpress_db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: nannal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    #container_name: "phpmyadmin"
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80
